# Generated by Django 4.2.20 on 2026-06-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_date"]},
        ),
    ]
